### PR TITLE
Support recursive types through Box'ing

### PR DESCRIPTION
**Pull request by davidpdrsn**
Fixes https://github.com/davidpdrsn/juniper-eager-loading/issues/22

`HasOne<Box<T>>` and `OptionHasOne<Box<T>>` are now supported.

### CODE REVIEW

**Comment by davidpdrsn** [comment]
@takeit This should fix the bug you reported. Are you able to test your project with this PR? Note that is requires version [`^0.4`](https://github.com/davidpdrsn/juniper-eager-loading/blob/master/CHANGELOG.md#040---2019-10-23). The code generation should just work with boxed types now but you can see a full example at https://github.com/davidpdrsn/juniper-eager-loading/blob/recursive-types/juniper-eager-loading/tests/recursive_types.rs

Let me know if you're having any issues.

**Comment by takeit** [comment]
Awesome @davidpdrsn ! I will test this and let you know. Thank you for the great work!

**Comment by davidpdrsn** [comment]
@takeit any news?

**Comment by takeit** [comment]
Not yet @davidpdrsn, sorry, I will take a look at it by the end of this week

**Comment by takeit** [comment]
hey @davidpdrsn I just checked this change and it works like a charm! Thanks!

**Comment by davidpdrsn** [comment]
Perfect! I'll ship a patch update right now.

**Comment by davidpdrsn** [comment]
@takeit [0.4.2](https://github.com/davidpdrsn/juniper-eager-loading/blob/master/CHANGELOG.md#042---2019-11-14) is shipped. Let me know if you find any other issues or have other suggestions for improvements 😊

**Comment by takeit** [comment]
Thanks @davidpdrsn ! Will do 😉 This is a really powerful and useful library 🚀

**Pull request merged**
